# Generated by Django 6.0.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os


def trainer_image_upload_path(instance, filename):
    trainer_id = str(instance.id) if instance.id else 'temp'
    return os.path.join("trainers", "images", trainer_id, filename)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=trainer_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('specializations', models.JSONField(default=list, help_text='لیست تخصص‌ها مثل: ["بدنسازی", "کراسفیت"]')),
                ('teaching_experience_years', models.PositiveIntegerField(default=0, help_text='سابقه تدریس به سال')),
                ('certifications', models.JSONField(default=list, help_text='لیست مدارک و گواهینامه‌ها مثل: ["مربیگری درجه 1", "مربیگری درجه 2"]')),
                ('special_expertise', models.JSONField(default=list, help_text='تخصص‌های ویژه مثل: ["کاهش وزن", "حجم", "توانبخشی"]')),
                ('active_students_count', models.PositiveIntegerField(default=0, help_text='تعداد شاگردان فعال')),
                ('bio', models.CharField(blank=True, help_text='تیتر کوتاه زیر اسم مربی', max_length=255)),
                ('average_rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('order_homepage', models.IntegerField(default=0, help_text='Order for homepage display (0 = use default sorting)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_gyms', models.ManyToManyField(blank=True, related_name='active_trainers', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerGroupPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('commission_rate', models.FloatField(default=0.05, help_text='Commission rate 0.05 is 5 percent')),
                ('sessions', models.IntegerField(default=0, help_text='Number of sessions')),
                ('order_homepage', models.IntegerField(default=0, help_text='Order for homepage display (0 = use default sorting)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='trainers.trainergrouppackage')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='trainers.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(i, str(i)) for i in range(1, 6)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('buyer', models.BooleanField(default=False, help_text='آیا از این مربی خرید داشته')),
                ('blocked', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trainers.trainerreview')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trainers.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Review',
                'verbose_name_plural': 'Trainer Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
