"""
Django settings for fitness project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

def _get_bool(value: str, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in ['1', 'true', 'yes', 'on']


def _get_list(value: str, default=None):
    if default is None:
        default = []
    if not value:
        return default
    return [item.strip() for item in value.split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool(os.getenv('DEBUG', 'True'))

SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-insecure-change-me'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')

ALLOWED_HOSTS = _get_list(os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else ''))
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be set when DEBUG is False.')

AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'accounts',
    'gyms',
    'finance',
    'interactions',
    'packages',
    'ticket',
    'discount',
    'notifications',
    'corsheaders',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fitness.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fitness.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.contrib.gis.db.backends.postgis'),
        'NAME': os.getenv('DB_NAME', 'fitness_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.getenv('SIMPLE_JWT_ACCESS_DAYS', '10'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('SIMPLE_JWT_REFRESH_DAYS', '30'))),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'fitness',
    'DESCRIPTION': 'API description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Authentication'},
        {'name': 'Gym'},
    ],
    'TAGS_SORTER': 'alpha',
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = _get_bool(os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False'))
CORS_ALLOWED_ORIGINS = _get_list(os.getenv('CORS_ALLOWED_ORIGINS', ''))

# In production we keep uploads under the collected static tree so the
# container can mount a persistent volume at /app/staticfiles/media.
MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/staticfiles/media/'

CSRF_TRUSTED_ORIGINS = _get_list(os.getenv('CSRF_TRUSTED_ORIGINS', ''))

CSRF_COOKIE_SECURE = _get_bool(os.getenv('CSRF_COOKIE_SECURE', str(not DEBUG)))
SESSION_COOKIE_SECURE = _get_bool(os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG)))
CSRF_COOKIE_HTTPONLY = False
CORS_ALLOW_CREDENTIALS = not CORS_ALLOW_ALL_ORIGINS

SECURE_SSL_REDIRECT = _get_bool(os.getenv('SECURE_SSL_REDIRECT', 'False'))
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_bool(os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', str(not DEBUG)))
SECURE_HSTS_PRELOAD = _get_bool(os.getenv('SECURE_HSTS_PRELOAD', str(not DEBUG)))
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True

# Melipayamak SMS
MELIPAYAMAK_API_KEY = os.getenv('MELIPAYAMAK_API_KEY', '')
MELIPAYAMAK_USERNAME = os.getenv('MELIPAYAMAK_USERNAME', '')
MELIPAYAMAK_PASSWORD = os.getenv('MELIPAYAMAK_PASSWORD', '')
MELIPAYAMAK_FROM = os.getenv('MELIPAYAMAK_FROM', '')

# Payment gateway
PAYMENT_GATEWAY_MERCHANT_ID = os.getenv('PAYMENT_GATEWAY_MERCHANT_ID', '')
PAYMENT_GATEWAY_ACCESS_TOKEN = os.getenv('PAYMENT_GATEWAY_ACCESS_TOKEN', '')
PAYMENT_GATEWAY_SANDBOX = _get_bool(os.getenv('PAYMENT_GATEWAY_SANDBOX', 'False'))
PAYMENT_GATEWAY_AMOUNT_MULTIPLIER = int(os.getenv('PAYMENT_GATEWAY_AMOUNT_MULTIPLIER', '1'))
PAYMENT_GATEWAY_CALLBACK_BASE_URL = os.getenv('PAYMENT_GATEWAY_CALLBACK_BASE_URL', '')
PAYMENT_GATEWAY_SUCCESS_REDIRECT_URL = os.getenv('PAYMENT_GATEWAY_SUCCESS_REDIRECT_URL', '')
PAYMENT_GATEWAY_FAILURE_REDIRECT_URL = os.getenv('PAYMENT_GATEWAY_FAILURE_REDIRECT_URL', '')

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "پشتیبانی فیت تیکت",
    "site_header": "پشتیبانی فیت تیکت",
    "site_brand": "پشتیبانی فیت تیکت",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "خوش آمدید به پنل مدیریت پشتیبانی فیت تیکت",
    "copyright": "پشتیبانی فیت تیکت",
    "search_model": ["accounts.User", "gyms.Gym", "finance.Purchase", "ticket.Ticket"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "خانه", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "وب‌سایت", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "پشتیبانی", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"name": "تغییر تم", "model": "auth.user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["accounts", "gyms", "finance", "packages", "ticket", "interactions", "discount"],
    "custom_links": {
        "accounts": [{
            "name": "گزارشات کاربران",
            "url": "admin:accounts_user_changelist",
            "icon": "fas fa-users",
            "permissions": ["accounts.view_user"]
        }]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.User": "fas fa-user-friends",
        "accounts.OTP": "fas fa-key",
        "gyms.Gym": "fas fa-dumbbell",
        "gyms.GymImage": "fas fa-images",
        "finance.Purchase": "fas fa-shopping-cart",
        "finance.Wallet": "fas fa-wallet",
        "finance.AdminWallet": "fas fa-coins",
        "finance.Transaction": "fas fa-exchange-alt",
        "finance.WithdrawRequest": "fas fa-money-bill-wave",
        "packages.Package": "fas fa-box",
        "packages.GroupPackage": "fas fa-layer-group",
        "ticket.Ticket": "fas fa-ticket-alt",
        "interactions.Review": "fas fa-star",
        "interactions.Favorite": "fas fa-heart",
        "discount.DiscountCode": "fas fa-tag",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-warning",
    "navbar": "navbar-warning",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ---------------------------------------------------------------------------
# Notifications — Scheduled Task (Plan Expiry)
# ---------------------------------------------------------------------------
# To enable the daily plan-expiry notifications, choose ONE of the options:
#
# Option A — django-crontab (add 'django_crontab' to INSTALLED_APPS):
#   INSTALLED_APPS += ['django_crontab']
#   CRONJOBS = [
#       ('0 6 * * *', 'notifications.tasks.send_plan_expiry_notifications'),
#   ]
#
# Option B — Celery beat (if Celery is already configured):
#   from celery.schedules import crontab
#   app.conf.beat_schedule['plan-expiry-notifications'] = {
#       'task': 'notifications.tasks.send_plan_expiry_notifications_task',
#       'schedule': crontab(hour=6, minute=0),
#   }
# ---------------------------------------------------------------------------
