### Accounts API Tests (Synced with actual URLs)

### Variables
@baseUrl = http://localhost:8000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTMzODU1LCJpYXQiOjE3NjE2Njk4NTUsImp0aSI6ImMwM2MyZDJiMTg1NDQ1ODFhODJmYTdjODhmMzUyOWIxIiwidXNlcl9pZCI6IjE1In0.OPpcE47Te7GniBKkAprLMGBOVJaoCdrwlqMG1JpAtMc

### 1. Request OTP (Public)
POST {{baseUrl}}/auth/request-otp/
Content-Type: application/json

{
    "phone": "09111111111"
}


### 2. Verify OTP -> Returns access/refresh tokens (Public)
POST {{baseUrl}}/auth/verify-otp/
Content-Type: application/json

{
    "phone": "09111111111",
    "code": "803634"
}

### 3. user Get Profile (Authenticated)
GET {{baseUrl}}/auth/profile/
Authorization: Bearer {{token}}
Content-Type: application/json


### 4. Edit Profile (Authenticated)
PUT {{baseUrl}}/auth/profile/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "full_name": "mmd",
    "birthdate": "1990-01-01"
}

### 5. Obtain JWT via SimpleJWT (Optional)
POST {{baseUrl}}/token/
Content-Type: application/json

{
    "phone": "09123456789",
    "password": "dummy-if-implemented"
}

### 6. Refresh JWT via SimpleJWT (Optional)
POST {{baseUrl}}/token/refresh/
Content-Type: application/json

{
    "refresh": "your_refresh_token_here"
}

# --------------------------------------------------------------
# ADMIN API Tests
# --------------------------------------------------------------
### 3. Get one Profile (Authenticated) admin role only
GET {{baseUrl}}/auth/profile/1
Authorization: Bearer {{token}}
Content-Type: application/json

### 4. all users list   
GET {{baseUrl}}/admin/users-list/
Authorization: Bearer {{token}}
Content-Type: application/json

### 7. Make User Staff (Superuser only)
POST {{baseUrl}}/admin/make-this-user-staff/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "phone": "09000000001",
    "is_staff": true
}
