### Gyms API Tests

### Variables
@baseUrl = http://localhost:8000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTMzNjY2LCJpYXQiOjE3NjE2Njk2NjYsImp0aSI6Ijk1ZjBkYWM2OTc0MzRmMTQ4MTA4M2MwMWNiMTY5NTYzIiwidXNlcl9pZCI6IjEzIn0.xkTWBGlnLKQ4XOZGJL4_4Mf6P6AEJspyly_hortqn90

@baseUrlmain = http://fitness.runflare.run/api


### 1. Get All Gyms
GET {{baseUrl}}/gym/gyms/



### 2. Create New Gym (Owner only)
POST {{baseUrlmain}}/gym/gyms/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "salamm",
    "owner": 13,
    "latitude":51.112121,
    "longitude":51.2121,
    "description": "A test gym for API testing",
    "address": "Test Address, Tehran, Iran",
    "working_hours": {
        "monday": "06:00-22:00",
        "tuesday": "06:00-22:00"

    }
}

### 3. Get Gym Details
GET {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}

### 4. Update Gym
PUT {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Updated Gym Name",
    "description": "Updated description",
    "address": "Updated Address"
}

### 5. Partial Update Gym
PATCH {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Partially Updated Name"
}

### 6. Delete Gym
DELETE {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}

### 7. Upload Gym Images
POST {{baseUrl}}/gym/images/upload/
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW



### 8. Find Nearest Gyms
POST {{baseUrl}}/gym/nearest-gyms/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude":51.0000,
    "longitude":51.2325
}
