### Gyms API Tests

### Variables
@baseUrl = http://localhost:8000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMzE2Nzc1LCJpYXQiOjE3NjEyMzAzNzUsImp0aSI6ImNhMTM4YWQwMWJiMjQ4ZDhiNjcwMjc3NzZjNmI2YjZmIiwidXNlcl9pZCI6IjYifQ.3V0B3nWvKdqj6PKH0g7Rsqec4K-3sNQKREIVhWYdPZQ

### 1. Get All Gyms
GET {{baseUrl}}/gym/gyms/



### 2. Create New Gym (Owner only)
POST {{baseUrl}}/gym/gyms/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "gym 2",
    "owner": 8,
    "latitude":51.112121,
    "longitude":51.2121,
    "description": "A test gym for API testing",
    "address": "Test Address, Tehran, Iran",
    "working_hours": {
        "monday": "06:00-22:00",
        "tuesday": "06:00-22:00"

    }
}

### 3. Get Gym Details
GET {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}

### 4. Update Gym
PUT {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Updated Gym Name",
    "description": "Updated description",
    "address": "Updated Address"
}

### 5. Partial Update Gym
PATCH {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Partially Updated Name"
}

### 6. Delete Gym
DELETE {{baseUrl}}/gym/gyms/1/
Authorization: Bearer {{token}}

### 7. Upload Gym Images
POST {{baseUrl}}/gym/images/upload/
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW



### 8. Find Nearest Gyms
POST {{baseUrl}}/gym/nearest-gyms/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "latitude":51.0000,
    "longitude":51.2325
}
