# Generated by Django 5.2.16 on 2026-08-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_initial'),
        ('packages', '0001_initial'),
        ('trainers', '0002_consolidated_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('gym', 'Gym Package'), ('trainer', 'Trainer Package')], default='gym', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='packages.package'),
        ),
        migrations.CreateModel(
            name='TrainerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='trainers.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='trainer_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.trainerwallet'),
        ),
        migrations.CreateModel(
            name='TrainerWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='توضیحات درخواست برداشت')),
                ('admin_message', models.TextField(blank=True, help_text='پیام ادمین درباره وضعیت درخواست')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_trainer_withdraw_requests', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='trainers.trainer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='finance.trainerwallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainerwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='check_trainer_wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='trainerwithdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='check_trainer_withdraw_amount_non_negative'),
        ),
    ]
