# Generated by Django 5.2.7 on 2025-10-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_review_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
