# Generated by Django 6.0.7 on 2026-07-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغ ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=2, help_text='برای درصدی: عدد کامل وارد کنید (مثلاً 5 برای 5٪) - برای مبلغ ثابت: مبلغ را به تومان وارد کنید', max_digits=10, verbose_name='مقدار تخفیف')),
                ('source_type', models.CharField(choices=[('club', 'از سهم باشگاه'), ('admin', 'از سهم ادمین')], max_length=10, verbose_name='نوع کسر تخفیف')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد مجاز کل استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد مجاز استفاده هر کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.gym', verbose_name='باشگاه مرتبط (درصورت وجود)')),
                ('packages', models.ManyToManyField(blank=True, related_name='discount_codes', to='packages.package', verbose_name='پکیج\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discountcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کاربران از کد تخفیف',
            },
        ),
        migrations.CreateModel(
            name='PackageDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغ ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=2, help_text='برای درصدی: عدد کامل وارد کنید (مثلاً 5 برای 5٪) - برای مبلغ ثابت: مبلغ را به تومان وارد کنید', max_digits=10, verbose_name='مقدار تخفیف')),
                ('source_type', models.CharField(choices=[('club', 'از سهم باشگاه'), ('admin', 'از سهم ادمین')], max_length=10, verbose_name='نوع کسر تخفیف')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='packages.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'تخفیف پکیج',
                'verbose_name_plural': 'تخفیف\u200cهای پکیج',
                'ordering': ['-created_at'],
            },
        ),
    ]
