# Generated by Django 5.2.7 on 2025-10-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0004_alter_gym_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('commission_rate', models.FloatField(default=0.05, help_text='Commission rate 0.05 is 5 percent')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='gyms.gym')),
            ],
        ),
    ]
