# Generated by Django 5.2.7 on 2025-10-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_average_rating_gym_comments'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='gym',
        ),
        migrations.AddField(
            model_name='package',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_packages', to='gyms.gym')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='group_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.grouppackage'),
            preserve_default=False,
        ),
    ]
