# Generated by Django 5.2.7 on 2025-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned_from_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
