# Generated by Django 5.2.7 on 2025-10-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_banned_from_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
