# Generated by Django 5.2.7 on 2025-10-02 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='longitude',
        ),
        migrations.AddField(
            model_name='gym',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
