# Generated by Django 5.2.7 on 2025-10-02 15:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_remove_gym_latitude_remove_gym_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
