# Generated by Django 5.2.7 on 2025-10-02 15:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_gym_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
