# Generated by Django 5.2.7 on 2025-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_gym_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gym',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
